import dbPromise from "@/modules/mongodb"

export default async function CreateBook(req, res) {
  console.log("Create Book")
  let {
    title,
    auth1,
    auth2,
    yearpublished,
    categories,
    bigskyaward,
    isbn,
    nominatedby,
    publisher,
    paddress1,
    paddress2,
    pcity,
    pstate,
    pzip,
    pcountry,
    pphone,
    pemail,
    aaddress1,
    aaddress2,
    acity,
    astate,
    azip,
    acountry,
    copyIds,
  } = JSON.parse(req.body)

  // console.log("books api")
  const newCopyIds = copyIds.split(",")
  copyIds = newCopyIds
  console.log(
    "books",
    title,
    auth1,
    auth2,
    yearpublished,
    categories,
    bigskyaward,
    isbn,
    nominatedby,
    publisher,
    paddress1,
    paddress2,
    pcity,
    pstate,
    pzip,
    pcountry,
    pphone,
    pemail,
    aaddress1,
    aaddress2,
    acity,
    astate,
    azip,
    acountry,
    copyIds
  )
  const dbConnection = await dbPromise
  const collection = await dbConnection.db().collection("books")
  const { insertedId } = await collection.insertOne({
    title,
    auth1,
    auth2,
    yearpublished,
    categories,
    bigskyaward,
    isbn,
    nominatedby,
    publisher,
    paddress1,
    paddress2,
    pcity,
    pstate,
    pzip,
    pcountry,
    pphone,
    pemail,
    aaddress1,
    aaddress2,
    acity,
    astate,
    azip,
    acountry,
    copyIds,
  })

  res.status(201).json({
    _id: insertedId.toString(),
    title,
    auth1,
    auth2,
    yearpublished,
    categories,
    bigskyaward,
    isbn,
    nominatedby,
    publisher,
    paddress1,
    paddress2,
    pcity,
    pstate,
    pzip,
    pcountry,
    pphone,
    pemail,
    aaddress1,
    aaddress2,
    acity,
    astate,
    azip,
    acountry,
    copyIds,
  })
}
